version: '3'
services:
    postgresql:
        image: postgres
        container_name: lesson
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=lesson
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
